<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $sofa   = Category::where('name', 'Sofa & Chair')->first();
        $lamp   = Category::where('name', 'Lamp & Vase')->first();
        $table  = Category::where('name', 'Table')->first();
        $wood   = Category::where('name', 'Wood Design')->first();
        $full   = Category::where('name', 'Full Interior')->first();

        $products = [
            [
                'category_id' => $sofa->id,
                'name'        => 'Premium Luxury Chair',
                'description' => 'A premium luxury chair designed for ultimate comfort and style.',
                'price'       => 122.75,
                'sale_price'  => null,
                'image'       => 'assets/img/gallery/shop-01/shop-04.jpg',
                'tag'         => 'Sale',
                'is_featured' => true,
                'stock'       => 15,
                'sku'         => 'CH-001',
            ],
            [
                'category_id' => $sofa->id,
                'name'        => 'Premium Luxury Sofa',
                'description' => 'A stunning luxury sofa that combines elegance with comfort.',
                'price'       => 122.75,
                'sale_price'  => 310.50,
                'image'       => 'assets/img/shortcode/product-card/pdct-02.jpg',
                'tag'         => 'NEW',
                'is_featured' => true,
                'stock'       => 8,
                'sku'         => 'SF-001',
            ],
            [
                'category_id' => $sofa->id,
                'name'        => 'White Minimal Chair',
                'description' => 'Clean and minimal white chair perfect for modern interiors.',
                'price'       => 122.75,
                'sale_price'  => 140.99,
                'image'       => 'assets/img/shortcode/product-card/pdct-01.jpg',
                'tag'         => null,
                'is_featured' => true,
                'stock'       => 20,
                'sku'         => 'CH-002',
            ],
            [
                'category_id' => $sofa->id,
                'name'        => 'Convertible Sofa',
                'description' => 'Versatile convertible sofa ideal for small spaces.',
                'price'       => 122.75,
                'sale_price'  => 140.99,
                'image'       => 'assets/img/home-v1/ftur-pdct-01.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 5,
                'sku'         => 'SF-002',
            ],
            [
                'category_id' => $sofa->id,
                'name'        => 'Modern Fashionable Sofa',
                'description' => 'Trendy and fashionable sofa for the modern home.',
                'price'       => 122.75,
                'sale_price'  => null,
                'image'       => 'assets/img/shortcode/product-card/pdct-02.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 12,
                'sku'         => 'SF-003',
            ],
            [
                'category_id' => $sofa->id,
                'name'        => 'Classic Chair',
                'description' => 'A timeless classic chair that complements any decor.',
                'price'       => 122.75,
                'sale_price'  => null,
                'image'       => 'assets/img/shortcode/product-card/pdct-01.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 18,
                'sku'         => 'CH-003',
            ],
            [
                'category_id' => $lamp->id,
                'name'        => 'Luxury Lamp for Wall',
                'description' => 'An elegant wall lamp that adds a warm glow to any room.',
                'price'       => 122.75,
                'sale_price'  => 140.99,
                'image'       => 'assets/img/gallery/shop-01/shop-06.jpg',
                'tag'         => 'OFF',
                'is_featured' => true,
                'stock'       => 30,
                'sku'         => 'LM-001',
            ],
            [
                'category_id' => $lamp->id,
                'name'        => 'Luxury Black Lamp for Wall',
                'description' => 'A sophisticated black wall lamp for modern interiors.',
                'price'       => 310.50,
                'sale_price'  => null,
                'image'       => 'assets/img/gallery/shop-01/shop-02.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 10,
                'sku'         => 'LM-002',
            ],
            [
                'category_id' => $lamp->id,
                'name'        => 'Flower Vase for Table',
                'description' => 'Beautiful flower vase that brightens up any table.',
                'price'       => 122.75,
                'sale_price'  => 140.99,
                'image'       => 'assets/img/home-v1/ftur-pdct-02.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 25,
                'sku'         => 'VS-001',
            ],
            [
                'category_id' => $lamp->id,
                'name'        => 'LED Table Lamp',
                'description' => 'Energy-efficient LED table lamp with modern design.',
                'price'       => 30.00,
                'sale_price'  => null,
                'image'       => 'assets/img/home-v5/latest-pdct-01.jpg',
                'tag'         => 'NEW',
                'is_featured' => true,
                'stock'       => 50,
                'sku'         => 'LM-003',
            ],
            [
                'category_id' => $lamp->id,
                'name'        => 'Classic Table Lamp',
                'description' => 'Timeless classic table lamp for living rooms and bedrooms.',
                'price'       => 120.00,
                'sale_price'  => null,
                'image'       => 'assets/img/shortcode/product-card/pdct-05.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 22,
                'sku'         => 'LM-004',
            ],
            [
                'category_id' => $table->id,
                'name'        => 'Table with Pops',
                'description' => 'A functional table with unique pop design elements.',
                'price'       => 122.75,
                'sale_price'  => 122.50,
                'image'       => 'assets/img/gallery/shop-01/shop-05.jpg',
                'tag'         => 'NEW',
                'is_featured' => true,
                'stock'       => 7,
                'sku'         => 'TB-001',
            ],
            [
                'category_id' => $table->id,
                'name'        => 'New Modern Luxury Table',
                'description' => 'A sleek modern luxury table that makes a bold statement.',
                'price'       => 132.75,
                'sale_price'  => 310.50,
                'image'       => 'assets/img/shortcode/product-card/pdct-08.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 4,
                'sku'         => 'TB-002',
            ],
            [
                'category_id' => $table->id,
                'name'        => 'Modern Long Table',
                'description' => 'Spacious modern long dining table for family gatherings.',
                'price'       => 122.75,
                'sale_price'  => 140.99,
                'image'       => 'assets/img/gallery/shop-01/shop-06.jpg',
                'tag'         => 'OFF',
                'is_featured' => false,
                'stock'       => 3,
                'sku'         => 'TB-003',
            ],
            [
                'category_id' => $full->id,
                'name'        => 'The Landscape House',
                'description' => 'Full interior package inspired by landscape architecture.',
                'price'       => 140.99,
                'sale_price'  => null,
                'image'       => 'assets/img/gallery/shop-01/shop-01.jpg',
                'tag'         => 'OFF',
                'is_featured' => false,
                'stock'       => 2,
                'sku'         => 'FI-001',
            ],
            [
                'category_id' => $full->id,
                'name'        => 'New Build Family Home',
                'description' => 'Complete furniture package for a new family home.',
                'price'       => 122.75,
                'sale_price'  => null,
                'image'       => 'assets/img/gallery/shop-01/shop-02.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 1,
                'sku'         => 'FI-002',
            ],
            [
                'category_id' => $wood->id,
                'name'        => 'Wooden Sofa',
                'description' => 'Handcrafted wooden sofa with natural finish.',
                'price'       => 132.75,
                'sale_price'  => null,
                'image'       => 'assets/img/home-v6/latest-pdct-02.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 6,
                'sku'         => 'WD-001',
            ],
            [
                'category_id' => $wood->id,
                'name'        => 'Modern Fashionable Wooden Sofa Chair',
                'description' => 'Fashionable wooden sofa chair with contemporary design.',
                'price'       => 122.75,
                'sale_price'  => null,
                'image'       => 'assets/img/shortcode/product-card/pdct-02.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 9,
                'sku'         => 'WD-002',
            ],
            [
                'category_id' => $sofa->id,
                'name'        => 'Classic Sofa',
                'description' => 'An enduring classic sofa perfect for any living room.',
                'price'       => 120.00,
                'sale_price'  => null,
                'image'       => 'assets/img/home-v5/latest-pdct-04.jpg',
                'tag'         => null,
                'is_featured' => true,
                'stock'       => 14,
                'sku'         => 'SF-004',
            ],
            [
                'category_id' => $lamp->id,
                'name'        => 'Premium White Vase',
                'description' => 'Elegant premium white vase for home decoration.',
                'price'       => 120.75,
                'sale_price'  => null,
                'image'       => 'assets/img/shortcode/product-card/pdct-11.jpg',
                'tag'         => null,
                'is_featured' => false,
                'stock'       => 35,
                'sku'         => 'VS-002',
            ],
        ];

        foreach ($products as $data) {
            $slug = Str::slug($data['name']);
            Product::firstOrCreate(['slug' => $slug], array_merge($data, ['slug' => $slug]));
        }
    }
}
