<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    public function show($title)
    {
        $products = [
            [
                'id' => 1,
                'img' => 'assets/img/gallery/shop-01/shop-03.jpg', 
                'price' => '$155.12', 
                'title' => 'Cat toy', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 2,
                'img' => 'assets/img/gallery/shop-01/shop-04.jpg', 
                'price' => '$122.75', 
                'title' => 'Premium Luxury Chair', 
                'rate' => '( 1,230 )', 
                'tag' => 'Sale', 
                'span' => 'false', 
            ],
            [
                'id' => 3,
                'img' => 'assets/img/gallery/shop-01/shop-05.jpg', 
                'price' => '$122.75 - $122.50', 
                'title' => 'Table with Pops', 
                'rate' => '( 1,230 )', 
                'tag' => 'NEW', 
                'span' => 'false', 
            ],
            [
                'id' => 4,
                'img' => 'assets/img/gallery/shop-01/shop-06.jpg', 
                'price' => '$122.75', 
                'title' => 'Luxury Lamp for Wall', 
                'rate' => '( 1,230 )', 
                'tag' => 'OFF', 
                'span' => 'true', 
            ],
            [
                'id' => 5,
                'img' => 'assets/img/shortcode/product-card/pdct-01.jpg', 
                'price' => '$122.75', 
                'title' => 'White Minimal Chair', 
                'rate' => '( 1,250 )', 
                'span' => 'true', 
            ],
            [
                'id' => 6,
                'img' => 'assets/img/shortcode/product-card/pdct-02.jpg', 
                'price' => '$122.75 - $310.50', 
                'title' => 'Premium Luxury Sofa', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 7,
                'img' => 'assets/img/shortcode/product-card/pdct-03.jpg', 
                'price' => '$122.75', 
                'title' => 'Table With Vas', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 8,
                'img' => 'assets/img/gallery/shop-01/shop-02.jpg', 
                'price' => '$310.50', 
                'title' => 'Luxury Black Lamp for Wall', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 9,
                'img' => 'assets/img/home-v1/ftur-pdct-01.jpg', 
                'price' => '$122.75', 
                'title' => 'Convertible Sofa', 
                'rate' => '( 1,230 )', 
                'span' => 'true', 
            ],
            [
                'id' => 10,
                'img' => 'assets/img/home-v1/ftur-pdct-02.jpg', 
                'price' => '$122.75 - $140.99', 
                'title' => 'Flower vase for Table', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 11,
                'img' => 'assets/img/shortcode/product-card/pdct-01.jpg', 
                'price' => '$122.75', 
                'title' => 'Premium Chair and Vase', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 12,
                'img' => 'assets/img/shortcode/product-card/pdct-02.jpg', 
                'price' => '$122.75', 
                'title' => 'Modern Fashionable Sofa', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 13,
                'img' => 'assets/img/shortcode/product-card/pdct-03.jpg', 
                'price' => '$122.75', 
                'title' => 'Vintage Table  With Vase', 
                'rate' => '( 1,230 )', 
                'span' => 'true', 
            ],
            [
                'id' => 14,
                'img' => 'assets/img/shortcode/product-card/pdct-03.jpg', 
                'price' => '$122.75', 
                'title' => 'Premium Chair and Vase1', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 15,
                'img' => 'assets/img/shortcode/product-card/pdct-04.jpg', 
                'price' => '$122.75', 
                'title' => 'Modern Fashionable Sofa1', 
                'rate' => '( 1,230 )', 
                'span' => 'true', 
            ],
            [
                'id' => 16,
                'img' => 'assets/img/shortcode/product-card/pdct-01.jpg', 
                'price' => '$122.75', 
                'title' => 'Classic Chair', 
                'rate' => '( 1,250 )', 
                'span' => 'false', 
            ],
            [
                'id' => 17,
                'img' => 'assets/img/shortcode/product-card/pdct-02.jpg', 
                'price' => '$122.75', 
                'title' => 'Modern Fashionable Wooden Sofa Chair', 
                'rate' => '( 1,250 )', 
                'span' => 'false', 
            ],
            [
                'id' => 18,
                'img' => 'assets/img/shortcode/product-card/pdct-03.jpg', 
                'price' => '$122.75', 
                'title' => 'Modern Wooden Sofa', 
                'rate' => '( 1,250 )', 
                'span' => 'false', 
            ],
            [
                'id' => 19,
                'img' => 'assets/img/shortcode/product-card/pdct-14.jpg', 
                'price' => '$122.75', 
                'title' => 'Vintage Light', 
                'rate' => '( 1,250 )', 
                'span' => 'true', 
            ],
            [
                'id' => 20,
                'img' => 'assets/img/shortcode/product-card/pdct-09.jpg', 
                'price' => '$122.75', 
                'title' => 'Fashionable Wooden Sofa', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 21,
                'img' => 'assets/img/shortcode/product-card/pdct-07.jpg', 
                'price' => '$122.75', 
                'title' => 'Premium Vase for Table', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 22,
                'img' => 'assets/img/shortcode/product-card/pdct-08.jpg', 
                'price' => '$132.75 - $310.50', 
                'title' => 'New Modern Luxury Table', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 23,
                'img' => 'assets/img/shortcode/product-card/pdct-07.jpg', 
                'price' => '$124.75', 
                'title' => 'Vintage Table / Chair for Pops', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 24,
                'img' => 'assets/img/shortcode/product-card/pdct-04.jpg', 
                'price' => '$120', 
                'title' => 'Classic Wall Clock', 
                'rate' => '( 123 )',
                'class' => 'bestSeller-item week',
            ],
            [
                'id' => 25,
                'img' => 'assets/img/shortcode/product-card/pdct-05.jpg', 
                'price' => '$120', 
                'title' => 'Classic Table Lamp', 
                'rate' => '( 123 )',
                'class' => 'bestSeller-item week',
            ],
            [
                'id' => 26,
                'img' => 'assets/img/home-v4/seller-02.jpg', 
                'price' => '$120', 
                'title' => 'Fashionable cool Sofa', 
                'rate' => '( 123 )',
                'class' => 'bestSeller-item week month bestSeller-big',
            ],
            [
                'id' => 27,
                'img' => 'assets/img/home-v4/seller-01.jpg', 
                'price' => '$120', 
                'title' => 'Vintage Table / Chair for Pops1', 
                'rate' => '( 123 )',
                'class' => 'bestSeller-item month',
            ],
            [
                'id' => 28,
                'img' => 'assets/img/shortcode/product-card/pdct-05.jpg', 
                'price' => '$120', 
                'title' => 'Classic Lamp', 
                'rate' => '( 123 )',
                'class' => 'bestSeller-item month',
            ],
            [
                'id' => 29,
                'img' => 'assets/img/home-v4/treading-01.jpg', 
                'price' => '$122.75', 
                'title' => 'Fashionable Woodens Sofa', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 30,
                'img' => 'assets/img/home-v4/treading-02.jpg', 
                'price' => '$122.75', 
                'title' => 'Vase for Table', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 31,
                'img' => 'assets/img/home-v4/treading-03.jpg', 
                'price' => '$122.75 - $310.50', 
                'title' => 'New Modern Luxury Table with Pops Lorem ipsum Furniture', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 32,
                'img' => 'assets/img/home-v4/treading-04.jpg', 
                'price' => '$122.75', 
                'title' => 'Vintage Table / Chair', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 33,
                'img' => 'assets/img/shortcode/product-card/pdct-06.jpg', 
                'price' => '$10', 
                'title' => 'Cercle Mirror', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 34,
                'img' => 'assets/img/home-v5/latest-pdct-01.jpg', 
                'price' => '$30', 
                'title' => 'LED Table Lamp', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 35,
                'img' => 'assets/img/home-v5/latest-pdct-02.jpg', 
                'price' => '$20', 
                'title' => 'Classic White Chir', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 36,
                'img' => 'assets/img/home-v5/latest-pdct-07.jpg', 
                'price' => '$80', 
                'title' => 'Mordern Sofa', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 37,
                'img' => 'assets/img/home-v5/latest-pdct-03.jpg', 
                'price' => '$60', 
                'title' => 'Fairy Lights', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 38,
                'img' => 'assets/img/home-v5/latest-pdct-04.jpg', 
                'price' => '$120', 
                'title' => 'Classic Sofa', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 39,
                'img' => 'assets/img/home-v5/latest-pdct-05.jpg', 
                'price' => '$20', 
                'title' => 'Classic Table Vase', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 40,
                'img' => 'assets/img/home-v5/latest-pdct-06.jpg', 
                'price' => '$56', 
                'title' => 'LED light', 
                'rate' => '( 123 )',
            ],
            [
                'id' => 41,
                'img' => 'assets/img/shortcode/product-card/pdct-10.jpg', 
                'price' => '$122.75', 
                'title' => 'Classic Lamp Light', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 42,
                'img' => 'assets/img/shortcode/product-card/pdct-11.jpg', 
                'price' => '$120.75', 
                'title' => 'Premium White Vase', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 43,
                'img' => 'assets/img/shortcode/product-card/pdct-12.jpg', 
                'price' => '$120.75 - $122.75', 
                'title' => 'New Modern Luxury Table with Pops Lorem Furniture', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 44,
                'img' => 'assets/img/home-v6/latest-pdct-01.jpg', 
                'price' => '$122.75', 
                'title' => 'The Watch ', 
                'rate' => '( 1,230 )', 
                'span' => 'true', 
            ],
            [
                'id' => 45,
                'img' => 'assets/img/home-v6/latest-pdct-02.jpg', 
                'price' => '$132.75', 
                'title' => 'Wooden Sofa', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 46,
                'img' => 'assets/img/home-v6/latest-pdct-03.jpg', 
                'price' => '$252.75', 
                'title' => 'Primum Vase for Table', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 47,
                'img' => 'assets/img/home-v6/latest-pdct-04.jpg', 
                'price' => '$122.75', 
                'title' => 'New Modern Luxury Chair', 
                'rate' => '( 1,230 )', 
                'span' => 'true', 
            ],
            [
                'id' => 48,
                'img' => 'assets/img/home-v6/latest-pdct-05.jpg', 
                'price' => '$122.75 - $140.99', 
                'title' => 'Chair for Pops', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
            ],
            [
                'id' => 49,
                'img' => 'assets/img/shortcode/product-card/pdct-04.jpg', 
                'price' => '$122.75', 
                'title' => 'The Premium Chair and Vase', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
                'data' => '100', 
            ],
            [
                'id' => 50,
                'img' => 'assets/img/shortcode/product-card/pdct-05.jpg', 
                'price' => '$122.75', 
                'title' => 'Card Fashionable Sofa', 
                'rate' => '( 1,230 )', 
                'span' => 'false', 
                'data' => '300', 
            ],
            [
                'id' => 51,
                'img' => 'assets/img/shortcode/product-card/pdct-06.jpg', 
                'price' => '$122.75', 
                'title' => 'Vintage Vase', 
                'rate' => '( 1,230 )', 
                'span' => 'true', 
                'data' => '500', 
            ],
            [
                'id' => 52,
                'img' => 'assets/img/shortcode/product-card/pdct-01.jpg', 
                'price' => '$25.75', 
                'title' => 'Mockup Collection', 
                'rate' => '( 1,230 )', 
                'tag' => 'Sale', 
                'span' => 'false', 
            ],
            [
                'id' => 53,
                'img' => 'assets/img/shortcode/product-card/pdct-02.jpg', 
                'price' => '$122.75', 
                'title' => 'Preminu Luxury Sofa', 
                'rate' => '( 1,230 )', 
                'tag' => 'NEW', 
                'span' => 'false', 
            ],
            [
                'id' => 54,
                'img' => 'assets/img/gallery/shop-01/shop-01.jpg', 
                'price' => '$140.99', 
                'title' => 'The Landscape House', 
                'rate' => '( 1,230 )', 
                'tag' => 'OFF', 
                'span' => 'false', 
            ],
            [
                'id' => 55,
                'img' => 'assets/img/gallery/shop-01/shop-02.jpg', 
                'price' => '$122.75', 
                'title' => 'New Build Family Home', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 56,
                'img' => 'assets/img/gallery/shop-01/shop-03.jpg', 
                'price' => '$140.99', 
                'title' => 'Private and Social Apartments', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 57,
                'img' => 'assets/img/gallery/shop-01/shop-04.jpg', 
                'price' => '$122.75', 
                'title' => 'Luxury Vase for Table', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 58,
                'img' => 'assets/img/gallery/shop-01/shop-05.jpg', 
                'price' => '$122.75 - $140.99', 
                'title' => 'Apartment Complex', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 59,
                'img' => 'assets/img/gallery/shop-01/shop-06.jpg', 
                'price' => '$122.75', 
                'title' => 'Modern Logn Table', 
                'rate' => '( 1,230 )', 
                'tag' => 'OFF1', 
                'span' => 'true', 
            ],
            [
                'id' => 60,
                'img' => 'assets/img/gallery/shop-01/shop-07.jpg', 
                'price' => '$122.75', 
                'title' => 'Construction Engineering', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 61,
                'img' => 'assets/img/gallery/shop-01/shop-08.jpg', 
                'price' => '$122.75', 
                'title' => 'The Blue Canton', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 62,
                'img' => 'assets/img/gallery/shop-01/shop-09.jpg', 
                'price' => '$122.75', 
                'title' => 'The Chrysler', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 63,
                'img' => 'assets/img/gallery/shop-01/shop-10.jpg', 
                'price' => '$122.75', 
                'title' => 'Purple Flatiron', 
                'rate' => '( 1,230 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 64,
                'img' => 'assets/img/gallery/shop-01/shop-05.jpg', 
                'price' => '$122.75 - $140.99', 
                'title' => 'Modern Luxury Table Lamp', 
                'rate' => '( 1,230 )', 
                'tag' => 'NEW', 
                'span' => 'false', 
            ],
            [
                'id' => 65,
                'img' => 'assets/img/shortcode/product-card/pdct-04.jpg', 
                'price' => '$25.75', 
                'title' => 'Rustic Reunion', 
                'rate' => '( 33 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 66,
                'img' => 'assets/img/shortcode/product-card/pdct-05.jpg', 
                'price' => '$122.75', 
                'title' => 'The Donald', 
                'rate' => '( 33 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 67,
                'img' => 'assets/img/shortcode/product-card/pdct-06.jpg', 
                'price' => '$140.99', 
                'title' => 'Red Tiny Hearst', 
                'rate' => '( 33 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 68,
                'img' => 'assets/img/shortcode/product-card/pdct-07.jpg', 
                'price' => '$122.75', 
                'title' => 'your development', 
                'rate' => '( 33 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 69,
                'img' => 'assets/img/shortcode/product-card/pdct-08.jpg', 
                'price' => '$140.99', 
                'title' => 'amazing partners', 
                'rate' => '( 33 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 70,
                'img' => 'assets/img/shortcode/product-card/pdct-09.jpg', 
                'price' => '$122.75', 
                'title' => 'Fully Responsive', 
                'rate' => '( 33 )', 
                'tag' => 'Sale', 
                'span' => 'false', 
            ],
            [
                'id' => 71,
                'img' => 'assets/img/shortcode/product-card/pdct-10.jpg', 
                'price' => '$122.75 - $140.99', 
                'title' => 'Browser Compatibility', 
                'rate' => '( 33 )', 
                'tag' => 'NEW', 
                'span' => 'false', 
            ],
            [
                'id' => 72,
                'img' => 'assets/img/shortcode/product-card/pdct-11.jpg', 
                'price' => '$122.75', 
                'title' => 'Retina Ready', 
                'rate' => '( 33 )', 
                'tag' => 'OFF', 
                'span' => 'true', 
            ],
            [
                'id' => 73,
                'img' => 'assets/img/shortcode/product-card/pdct-12.jpg', 
                'price' => '$122.75', 
                'title' => 'Mortgage Advisor', 
                'rate' => '( 33 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 74,
                'img' => 'assets/img/shortcode/product-card/pdct-13.jpg', 
                'price' => '$122.75', 
                'title' => 'Branch Registration', 
                'rate' => '( 33 )', 
                'tag' => '', 
                'span' => 'false', 
            ],
            [
                'id' => 75,
                'img' => 'assets/img/gallery/shop-04/shop-01.jpg', 
                'price' => '$122.75', 
                'title' => 'Design your apps', 
                'rate' => '( 123 )', 
                'tag' => 'OFF', 
                'span' => 'true', 
                'class' => 'shop-item Interior', 
            ],
            [
                'id' => 76,
                'img' => 'assets/img/gallery/shop-04/shop-02.jpg', 
                'price' => '$122.75', 
                'title' => 'your own way', 
                'rate' => '( 123 )', 
                'tag' => '', 
                'span' => 'false', 
                'class' => 'shop-item', 
            ],
            [
                'id' => 77,
                'img' => 'assets/img/gallery/shop-04/shop-03.jpg', 
                'price' => '$122.75', 
                'title' => 'Smartest Applications', 
                'rate' => '( 123 )', 
                'tag' => 'OFF', 
                'span' => 'true', 
                'class' => 'shop-item Interior Vase Table', 
            ],
            [
                'id' => 78,
                'img' => 'assets/img/gallery/shop-04/shop-04.jpg', 
                'price' => '$122.75', 
                'title' => 'For Business', 
                'rate' => '( 123 )', 
                'tag' => '', 
                'span' => 'false', 
                'class' => 'shop-item Table Design', 
            ],
            [
                'id' => 79,
                'img' => 'assets/img/gallery/shop-04/shop-05.jpg', 
                'price' => '$122.75', 
                'title' => 'Change Your Strategy', 
                'rate' => '( 123 )', 
                'tag' => 'OFF', 
                'span' => 'true', 
                'class' => 'shop-item Interior Table', 
            ],
            [
                'id' => 80,
                'img' => 'assets/img/gallery/shop-04/shop-06.jpg', 
                'price' => '$122.75', 
                'title' => 'Provide denounce', 
                'rate' => '( 123 )', 
                'tag' => '', 
                'span' => 'false', 
                'class' => 'shop-item Vase', 
            ],
            [
                'id' => 81,
                'img' => 'assets/img/gallery/shop-04/shop-07.jpg', 
                'price' => '$122.75', 
                'title' => 'Offer Prognosis', 
                'rate' => '( 123 )', 
                'tag' => '', 
                'span' => 'false', 
                'class' => 'shop-item Table Design', 
            ],
            [
                'id' => 82,
                'img' => 'assets/img/gallery/shop-04/shop-08.jpg', 
                'price' => '$122.75', 
                'title' => 'Mobile Marketing', 
                'rate' => '( 123 )', 
                'tag' => '', 
                'span' => 'false', 
                'class' => 'shop-item Vase', 
            ],
            [
                'id' => 83,
                'img' => 'assets/img/gallery/shop-04/shop-09.jpg', 
                'price' => '$122.75', 
                'title' => 'You Covered', 
                'rate' => '( 123 )', 
                'tag' => '', 
                'span' => 'false', 
                'class' => 'shop-item Table Design', 
            ]
        ];

        // Find the product by ID
        $item = collect($products)->first(function ($product) use ($title) {
            return Str::slug($product['title']) === $title;
        });

        // If product not found, return 404 error
        if (!$item) {
            abort(404);
        }

        // Return the view and pass the product data to the view
        return view('product-details', compact('item'));
    }
}